# ./docker-compose.yml

version: '3'

services:
  db:
    container_name: "aoggbackoffice-db"
    image: mysql:5.7
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
      MYSQL_USER: stock
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  web:
    container_name: "aoggbackoffice-web"
    image: php:7.2.2-apache
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true